name: Build Dungeon Game

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up C Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make

      - name: Link dungeon object file
        run: cp dungeon_X86_64.o dungeon.o

      - name: Compile project
        run: make
